BootSound_NAME = BootSound
BootSound_FILES = BootSound.m
BootSound_CFLAGS = -fobjc-arc -DTHEOS_LEAN_AND_MEAN
BootSound_FRAMEWORKS = Foundation
BootSound_EXTRA_FRAMEWORKS = Cephei

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk
